### ISSUE TITLE
Does not seem to be working?

### ISSUE THREAD

**Issue by nekromoff** [wesleywerner/ancient-tech#1]
I tried different browsers, but it does not seem to be working (localhost).

**Comment by wesleywerner** [comment]
Enter the src/ directory and run a simple http server `python -m SimpleHTTPServer` then you can browse on `http://localhost:8000/`

This compo entry is unfinished, the idea was a freeciv-inspired clicker game. But as you can tell I only started on it 😞 The only and notable feature is a working tech tree you can click through. There is no charge for research, discreet time passing or events.

**Comment by nekromoff** [comment]
Thanks for the response, I'll try it anyway!
